# Generated by Django 4.2.7 on 2023-11-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
